create table if not exists public.answers (
  id bigint generated by default as identity primary key,

  ticket_number integer not null unique
    check (ticket_number between 1 and 100),

  base_sake integer not null,

  flavor1_sake integer not null,

  flavor1_amount integer not null
    check (flavor1_amount > 0),

  flavor2_sake integer not null,

  flavor2_amount integer not null
    check (flavor2_amount > 0),

  created_at timestamptz not null default now(),

  constraint different_items check (
    base_sake <> flavor1_sake
    and base_sake <> flavor2_sake
    and flavor1_sake <> flavor2_sake
  )
);

alter table public.answers enable row level security;

grant usage on schema public
to anon, authenticated;

grant select, insert, update
on table public.answers
to anon, authenticated;

grant delete
on table public.answers
to authenticated;

revoke delete
on table public.answers
from anon;

grant usage, select
on all sequences in schema public
to anon, authenticated;

create policy "participants_can_read_answers"
on public.answers
for select
to anon
using (true);

create policy "participants_can_submit_answers"
on public.answers
for insert
to anon
with check (true);

create policy "participants_can_update_answers"
on public.answers
for update
to anon
using (true)
with check (true);

create policy "authenticated_users_can_read_answers"
on public.answers
for select
to authenticated
using (true);

create policy "authenticated_users_can_submit_answers"
on public.answers
for insert
to authenticated
with check (true);

create policy "authenticated_users_can_update_answers"
on public.answers
for update
to authenticated
using (true)
with check (true);
