create table if not exists public.answers (
  id bigint generated by default as identity primary key,

  ticket_number integer not null unique
    check (ticket_number between 1 and 100),

  base_sake integer not null,

  flavor1_sake integer not null,

  flavor1_amount integer not null
    check (flavor1_amount > 0),

  flavor2_sake integer not null,

  flavor2_amount integer not null
    check (flavor2_amount > 0),

  created_at timestamptz not null default now(),

  constraint different_items check (
    base_sake <> flavor1_sake
    and base_sake <> flavor2_sake
    and flavor1_sake <> flavor2_sake
  )
);

alter table public.answers enable row level security;

grant usage on schema public
to anon, authenticated;

grant select, insert, update
on table public.answers
to anon, authenticated;

grant delete
on table public.answers
to authenticated;

revoke delete
on table public.answers
from anon;

grant usage, select
on all sequences in schema public
to anon, authenticated;

create policy "participants_can_read_answers"
on public.answers
for select
to anon
using (true);

create policy "participants_can_submit_answers"
on public.answers
for insert
to anon
with check (true);

create policy "participants_can_update_answers"
on public.answers
for update
to anon
using (true)
with check (true);

create policy "authenticated_users_can_read_answers"
on public.answers
for select
to authenticated
using (true);

create policy "authenticated_users_can_submit_answers"
on public.answers
for insert
to authenticated
with check (true);

create policy "authenticated_users_can_update_answers"
on public.answers
for update
to authenticated
using (true)
with check (true);

create table if not exists public.event_settings (
  id integer primary key
    check (id = 1),

  participant_count integer not null default 30
    check (
      participant_count between 1 and 30
    ),

  organizer_ticket integer not null default 30
    check (
      organizer_ticket between 1 and 30
    ),

  updated_at timestamptz not null default now(),

  constraint organizer_within_participant_count
    check (
      organizer_ticket <= participant_count
    )
);

insert into public.event_settings (
  id,
  participant_count,
  organizer_ticket
)
values (
  1,
  30,
  30
)
on conflict (id) do nothing;

alter table public.event_settings
enable row level security;

grant select
on table public.event_settings
to anon, authenticated;

grant update
on table public.event_settings
to authenticated;

revoke insert, update, delete
on table public.event_settings
from anon;

create policy "participants_can_read_event_settings"
on public.event_settings
for select
to anon
using (id = 1);

create policy "authenticated_users_can_read_event_settings"
on public.event_settings
for select
to authenticated
using (id = 1);

create policy "authenticated_users_can_update_event_settings"
on public.event_settings
for update
to authenticated
using (id = 1)
with check (
  id = 1
  and participant_count between 1 and 30
  and organizer_ticket between 1
    and participant_count
);
